account/urls.py
from django.conf import urls
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.urls import path, reverse_lazy, include

from . import views

app_name = "blog"

urlpatterns = [
    # path("login/", views.login_user, name="login"),
    # path("login/", auth_views.LoginView.as_view(), name="login"),
    # path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path(
        "password_change/",
        auth_views.PasswordChangeView.as_view(
            success_url=reverse_lazy("account:password_change_done"),
        ),
        name="password_change",
    ),
    # path(
    #     "password_change/done/",
    #     auth_views.PasswordChangeDoneView.as_view(),
    #     name="password_change_done",
    # ),
    path(
        "password_reset/",
        auth_views.PasswordResetView.as_view(
            success_url=reverse_lazy("account:password_reset_done"),
        ),
        name="password_reset",
    ),
    # path(
    #     "password_reset/done/",
    #     auth_views.PasswordResetDoneView.as_view(),
    #     name="password_reset_done",
    # ),
    path(
        "reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            success_url=reverse_lazy("account:password_reset_complete"),
        ),
        name="password_reset_confirm",
    ),
    # path(
    #     "reset/done/",
    #     auth_views.PasswordResetCompleteView.as_view(),
    #     name="password_reset_complete",
    # ),
    path("register/", views.register, name="register"),
    path("edit/", views.edit, name="edit"),
    path("", include("django.contrib.auth.urls")),
    path("", views.dashboard, name="dashboard"),
]

# dummypassword
# testpassword

blog/urls.py
from django.urls import path

from . import views
from .feeds import LatestPostsFeed

app_name = "blog"

urlpatterns = [
    path("", views.post_list, name="post_list"),
    # RSS feed
    path("feed/", LatestPostsFeed(), name="post_feed"),
    path("tag/<slug:tag_slug>/", views.post_list, name="post_list_by_tag"),
    # path("", views.PostListView.as_view(), name="post_list"),
    path("<int:post_id>/share/", views.post_share, name="post_share"),
    path("search/", views.post_search, name="post_search"),
    path("<slug:slug>/", views.post_detail, name="post_detail"),
]

main/urls.py
from django.contrib import admin, sitemaps
from django.contrib.sitemaps.views import sitemap
from django.urls import path
from django.urls.conf import include
from django.conf.urls.static import static
from django.utils.translation import gettext_lazy as _
from django.conf.urls.i18n import i18n_patterns

from blog.sitemaps import PostSitemap
from main.settings import MEDIA_URL, MEDIA_ROOT, DEBUG

from . import views

sitemaps = {
    "posts": PostSitemap,
}

urlpatterns = i18n_patterns(
    path(_("admin/"), admin.site.urls),
    path("rosetta/", include("rosetta.urls")),
    path(_("blog/"), include("blog.urls", namespace="blog")),
    path(_("account/"), include("account.urls", namespace="account")),
    path(_("shop/"), include("shop.urls", namespace="shop")),
    path(_("social-auth/"), include("social_django.urls", namespace="social")),
    path(_("cart/"), include("cart.urls", namespace="cart")),
    path(_("orders/"), include("orders.urls", namespace="orders")),
    path(_("payments/"), include("payments.urls", namespace="payments")),
    path(_("coupons/"), include("coupons.urls", namespace="coupons")),
    path(
        "language/change/<str:language_code>/",
        views.change_language,
        name="change_language",
    ),
    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
)

urlpatterns += static(MEDIA_URL, document_root=MEDIA_ROOT)

account/models.py
from django.conf.global_settings import AUTH_USER_MODEL, TEST_RUNNER
from django.db import models


class Profile(models.Model):
    user = models.OneToOneField(AUTH_USER_MODEL, on_delete=models.CASCADE)
    date_of_birth = models.DateField(blank=True, null=True)
    photo = models.ImageField(upload_to="users/%Y/%m/%d/", blank=True)

    def __str__(self) -> str:
        return f"{self.user.username}'s profile"

account/forms.py
from django import forms
from django.contrib.auth.models import User
from django.forms import fields, widgets

from .models import Profile


class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)


class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(label="Password", widget=forms.PasswordInput)
    password2 = forms.CharField(label="Repeat password", widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ("username", "first_name", "email")

    def clean_password2(self):
        cd = self.cleaned_data
        if cd.get("password") != cd.get("password2"):
            raise forms.ValidationError("Passwords don't match")
        return cd.get("password2")


class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ("first_name", "last_name", "email")


class ProfileEditform(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ("date_of_birth", "photo")
        widgets = {
            "date_of_birth": widgets.DateInput(attrs={"type": "date"}),
        }

account/views.py
from django.contrib import auth
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import render
from django.contrib import messages

from .forms import LoginForm, ProfileEditform, UserEditForm, UserRegistrationForm
from .models import Profile


def login_user(request):
    if request.method == "POST":
        form = LoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(
                request, username=cd.get("username"), password=cd.get("password")
            )
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return HttpResponse("Authenticated successfully")
                else:
                    return HttpResponse("Disabled account")
            else:
                return HttpResponse("Invalid login")
    else:
        form = LoginForm()
    return render(request, "account/login.html", {"form": form})


def register(request):
    if request.method == "POST":
        user_form = UserRegistrationForm(request.POST)
        if user_form.is_valid():
            new_user = user_form.save(commit=False)
            new_user.set_password(user_form.cleaned_data["password"])
            new_user.save()
            Profile.objects.create(user=new_user)
            return render(request, "register_done.html", {"new_user": new_user})
    else:
        user_form = UserRegistrationForm()
        return render(request, "register.html", {"user_form": user_form})


@login_required
def dashboard(request):
    return render(request, "account/dashboard.html", {"section": "dashboard"})


@login_required
def edit(request):
    user = request.user
    if request.method == "POST":
        user_form = UserEditForm(instance=user, data=request.POST)
        profile_form = ProfileEditform(
            instance=user.profile, data=request.POST, files=request.FILES
        )
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, "Profile updated successfully")
        else:
            messages.error(request, "Error updating your profile")
    else:
        user_form = UserEditForm(instance=user)
        profile_form = ProfileEditform(instance=user.profile)
    return render(
        request,
        "account/edit.html",
        {"user_form": user_form, "profile_form": profile_form},
    )

account/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <title>{% block title %}{% endblock %}</title>
    <link href="{% static "css/styles.css" %}" rel="stylesheet">
  </head>
  <body>
    <div id="header">
      <span class="logo">Social</span>
      {% if request.user.is_authenticated %}
        <ul class="menu">
          <li {% if section == "dashboard" %}class="selected"{% endif %}>
            <a href="{% url "account:dashboard" %}">My dashboard</a>
          </li>
          <li {% if section == "images" %}class="selected"{% endif %}>
            <a href="#">Images</a>
          </li>
          <li {% if section == "people" %}class="selected"{% endif %}>
            <a href="#">People</a>
          </li>
        </ul>
      {% endif %}

      <span class="user">
        {% if request.user.is_authenticated %}
          Hello {{ request.user.first_name }},
          <a href="{% url "account:logout" %}">Logout</a>
        {% else %}
          <a href="{% url "account:login" %}">Log in</a>
        {% endif %}
      </span>
    </div>

    {% if messages %}
      <ul class="messages">
      {% for message in messages %}
        <li class="{{ message.tags }}">
        {{ message|safe }}
        <a href="#" class="close">x</a>
        </li>
      {% endfor %}
      </ul>
    {% endif %}

    <div id="content">
      {% block content %}
      {% endblock %}
    </div>
  </body>
</html>

account/templates/register.html
{% extends "base.html" %}

{% block title %}Create an account{% endblock %}

{% block content %}
    <h1>Create an account</h1>
    <p>Please, sign up using the following form:</p>
    <form method="post">
        {{ user_form.as_p }}
        {% csrf_token %}
        <p><input type="submit" value="Create my account"></p>
    </form>
{% endblock %}

account/templates/register_done.html
{% extends "base.html" %}

{% block title %}Welcome{% endblock %}

{% block content %}
    <h1>Welcome {{ new_user.first_name }}!</h1>
    <p>Your account has been successfully created. Now you can <a
    href="{% url "account:login" %}">log in</a>.</p>
{% endblock %}